// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RefreshToken is an autogenerated mock type for the RefreshToken type
type RefreshToken struct {
	mock.Mock
}

// Create provides a mock function with no fields
func (_m *RefreshToken) Create() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewRefreshToken creates a new instance of RefreshToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshToken {
	mock := &RefreshToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
