// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	model "go-api-example/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// TodoUsecase is an autogenerated mock type for the TodoUsecase type
type TodoUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *TodoUsecase) Create(ctx context.Context, req *model.CreateTodoRequest) (*model.TodoResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.TodoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateTodoRequest) (*model.TodoResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.CreateTodoRequest) *model.TodoResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TodoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.CreateTodoRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, req
func (_m *TodoUsecase) FindByID(ctx context.Context, req *model.GetTodoRequest) (*model.TodoResponse, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *model.TodoResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetTodoRequest) (*model.TodoResponse, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.GetTodoRequest) *model.TodoResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TodoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.GetTodoRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, req
func (_m *TodoUsecase) List(ctx context.Context, req *model.SearchTodoRequest) ([]model.TodoResponse, int, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.TodoResponse
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.SearchTodoRequest) ([]model.TodoResponse, int, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.SearchTodoRequest) []model.TodoResponse); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TodoResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.SearchTodoRequest) int); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *model.SearchTodoRequest) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UpdateByID provides a mock function with given fields: ctx, req
func (_m *TodoUsecase) UpdateByID(ctx context.Context, req *model.UpdateTodoRequest) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.UpdateTodoRequest) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTodoUsecase creates a new instance of TodoUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTodoUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TodoUsecase {
	mock := &TodoUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
