// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	db "go-api-example/internal/db"

	mock "github.com/stretchr/testify/mock"
)

// Transactioner is an autogenerated mock type for the Transactioner type
type Transactioner struct {
	mock.Mock
}

// Do provides a mock function with given fields: ctx, fn
func (_m *Transactioner) Do(ctx context.Context, fn func(db.Executor) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(db.Executor) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTransactioner creates a new instance of Transactioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transactioner {
	mock := &Transactioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
